### PR TITLE
Add Clear button to action bar

### PR DESCRIPTION
**Pull request by Ahsieh95**
Code to add clear complete button in action bar in Xml line 21-27

### CODE REVIEW

**Comment by spacecowboy** [comment]
Thanks for the PR!

This is a duplicate of the menu action present here:
https://github.com/spacecowboy/NotePad/blob/master/app/src/main/res/menu/fragment_tasklist.xml#L24

I am also not sure about using an 'X' for this icon, which is one reason why it doesn't have one at the moment. I'd be happy to hear a counter-argument though.

**Comment by Akai-Karasu** [comment]
I seem to have forgotten to mention this was in response to issue #348. I understand regarding the icon. As a suggestion, would a checked checkbox work in place of the 'X' icon?

**Comment by spacecowboy** [comment]
Maybe. What do you think of the double checkbox? 

ic_done_all

<https://github.com/google/material-design-icons/blob/master/action/drawable-anydpi-v21/ic_done_all_black_24dp.xml> (needs color flipped to white though)

**Comment by Akai-Karasu** [comment]
That would work but I feel it's more of a complete all rather than a clear complete.

**Comment by Akai-Karasu** [comment]
Actually I realise that what I suggested earlier would be more of a complete all. The double checkbox makes more sense.

**Pull request closed without merging**
