### PR TITLE
fix for #336

### PR DESCRIPTION
**Pull request by ggao2014**
this is a fix for issue#336, it opens alllist after deleting a list

### CODE REVIEW

**Comment by ggao2014** [comment]
it only adds three lines of code to NotePad/app/src/main/java/com/nononsenseapps/notepad/ui/common/DialogDeleteList.java

**Comment by spacecowboy** [comment]
Great! Thanks for the PR. Those 3 lines look fine but there are a lot of other changes (mainly info-prints by the looks of it). Any chance you could isolate the change to the three lines in question?

**Comment by ggao2014** [comment]
I've made a new branch that isolates the change to the three lines.

**Comment by spacecowboy** [comment]
replaced by #378

**Pull request closed without merging**
