### PR TITLE
Version 6.0

### PR DESCRIPTION
**Pull request by spacecowboy**
This is a major release which does not make sense to release in separate pieces. The goal is a major simplification and generalization of the app. 
## Milestones:
- [ ] Upgrade app to Material Design

The current design of the app was made for the release of Ice Cream Sandwhich and the Holo theme and while it's still way better than the old Gingerbread themes, it has fallen behind the current standard.
- [x] Remove dependency on Play Services
  - [x] Remove location reminders

Play Services, and location reminders which depend on it, is the reason no material design update has been possible before. Play Services is a proprietary closed source package, which makes me uncomfortable for other reasons.
- [ ] Change to having multiple sources for tasks instead of merging several stuff into one database
  - [ ] Remove local database source
  - [ ] Create GTasks provider
  - [ ] Create SD-card Org provider
  - [ ] Create Dropbox Org provider module (needs to be separated out to allow free version)

Current design is that you can sync with multiple sources (GTasks, SD-card, Dropbox) and they all merge into a single set of lists/files. This of course means merge conflicts, which cannot be handled nicely. The new design will separate the services completely, and you will be able to select which one you are working with, much like selecting your email account in GMail.
- [ ] Implement graceful migration from current database structure

Local notes with no remote equivalent will simply be moved to Local SD-card equivalent.

It is possible that the archive and time machine features will need to be removed.
- [x] Stop using AndroidAnnotations

This keeps breaking. Easier to get rid of it.
- [ ] Figure out how reminders are handled

Possible an optional feature of providers. Otherwise, keep data locally.
### Stuff to remember:
- [ ] Dashclock
- [ ] AndroidAgendaWidget
- [ ] Widget

### CODE REVIEW

**Comment by licaon-kter** [comment]
How is https://github.com/spacecowboy/NotePad/issues/308 integrated in these milestones?

Can the *Org provider* even support this: https://github.com/spacecowboy/NotePad/issues/306 ?

**Comment by spacecowboy** [comment]
@licaon-kter The new structure will be more generalized, and it will be easier to add support for other services than it is now. Hopefully, even for people other than myself.

#306 is not impacted in any special way. But it's good that you raised the point as I need to think about how it should be done (in general).

**Comment by licaon-kter** [comment]
Tried it on 4.4.4, it should work, right?
Starts ok, but once I set the Sync folder (either an existing one with files or created one) it will FC on start ( I guess on sync ).

**Comment by spacecowboy** [comment]
@licaon-kter What crashes? The latest beta? (I'm confused, since this PR is completely unreleated to that).

Please create a new issue if you've found a problem (sorry about telling you otherwise at an earlier time, I changed my mind about that)

https://github.com/spacecowboy/NotePad/milestones/6.0

**Comment by licaon-kter** [comment]
New build?

**Pull request closed without merging**
